format = """
$username\
$directory\
$git_branch\
$git_status\
$package\
$fill\
$docker_context\
$lua\
$c\
$java\
$cmd_duration\
$jobs\
\n$character
"""
palette = "catppuccin_frappe"

[username]
show_always = true
style_user = 'bold mauve'


[git_branch]
symbol = ' '
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[java]
symbol = ' '

[lua]
symbol = ' '

[c]
symbol = ' '
detect_extensions = ['c', 'h', 'cpp', 'hpp']
commands =  [ [ 'cc', '--version'], [ 'gcc', '--version' ], [ 'g++', '--version' ] ]

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'overlay0'
format = '[$duration]($style)'

[jobs]
symbol = '%'
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

# Starship modules
[character]
success_symbol = "[[󰄛](teal) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
